# Generated by Django 4.1 on 2023-03-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_instructorprofile'),
        ('course_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='user_service.instructorprofile'),
        ),
    ]
