# Generated by Django 4.1 on 2023-03-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0002_course_instructor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor_id',
            new_name='instructor',
        ),
    ]
