# Generated by Django 4.1 on 2023-04-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0008_alter_course_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
