# Generated by Django 4.1 on 2023-04-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0010_alter_course_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED')], max_length=20, null=True),
        ),
    ]
