# Generated by Django 4.1 on 2023-04-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0011_alter_course_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20, null=True),
        ),
    ]
