# Generated by Django 4.1 on 2023-04-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0012_alter_course_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
