# Generated by Django 4.1 on 2023-04-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0013_alter_course_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
