# Generated by Django 4.1 on 2023-04-14 22:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_alter_instructorprofile_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_service', '0014_alter_course_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorSkill',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('skill_name', models.CharField(blank=True, max_length=40, null=True)),
                ('skill_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insructor_skill', to='user_service.instructorprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SkillCertification',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('certification_name', models.CharField(max_length=50)),
                ('certification_date', models.DateField()),
                ('certificate_file', models.ImageField(blank=True, null=True, upload_to='')),
                ('skill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_certification', to='course_service.instructorskill')),
            ],
        ),
    ]
