# Generated by Django 4.1 on 2023-04-15 11:19

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0015_instructorskill_alter_review_user_skillcertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='module_service/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course_service.course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='skillcertification',
            name='certificate_file',
            field=models.ImageField(blank=True, null=True, upload_to='user_service/instructor/certificates/'),
        ),
        migrations.CreateModel(
            name='TagModule',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_service.module')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_service.tag')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='tags',
            field=models.ManyToManyField(through='course_service.TagModule', to='course_service.tag'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['id'], name='course_serv_id_5ef479_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['created_at'], name='course_serv_created_94876f_idx'),
        ),
    ]
