# Generated by Django 4.1 on 2023-04-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0017_alter_module_tags_alter_module_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='tags',
            field=models.ManyToManyField(blank=True, through='course_service.TagModule', to='course_service.tag'),
        ),
    ]
