# Generated by Django 4.1 on 2023-04-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0018_alter_module_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcertification',
            options={'ordering': ('skill__instructor',)},
        ),
    ]
