# Generated by Django 4.1 on 2023-04-25 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0020_alter_course_options_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorskill',
            options={'ordering': ['-skill_level']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterField(
            model_name='instructorskill',
            name='skill_level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
