# Generated by Django 4.1 on 2023-04-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0022_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('updated_at',), 'verbose_name_plural': 'Quizes'},
        ),
    ]
