# Generated by Django 4.1 on 2023-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_instructorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_service/instructor/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_service/student/profile_pictures/'),
        ),
    ]
