# Generated by Django 4.1 on 2023-05-09 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_alter_instructorprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_two_factor_authentication',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smscode', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
